-- 사이트 방문 로그(방문자수 통계용).
-- 서버(Next.js /api/visit, service_role)에서만 기록/조회한다. RLS 잠금(익명 공개 없음).
-- Supabase SQL 에디터에서 1회 실행:
--   https://supabase.com/dashboard/project/jeqvxzkvumkiraclauvo/sql/new

create table if not exists public.site_visit (
    id bigint generated by default as identity primary key,
    path text,
    created_at timestamptz not null default now()
);

create index if not exists idx_site_visit_created_at
    on public.site_visit (created_at);

alter table public.site_visit enable row level security;
-- 정책을 열지 않으므로 anon/authenticated 는 접근 불가. service_role(서버)만 가능.